spring:
  application:
    name: no-loose-coins
  datasource:
    url:  jdbc:${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never



server:
  port: ${PORT}
