spring:
  flyway:
    enabled: true
    locations: filesystem:${TEST_SCRIPT_FLYWAY_DIR}
    baseline-on-migrate: true
  application:
    name: no-loose-coins
  datasource:
    url: jdbc:h2:mem:service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

security:
  token:
    issuer: ${JWT_ISSUER}
    expiration: ${EXPIRATION_TIME}
    secret: ${JWT_SECRET}