spring:
  application:
    name: no-loose-coins

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
    locations: db/migration/postgree


server:
  port: ${PORT}


security:
  token:
    issuer: ${JWT_ISSUER}
    expiration: ${EXPIRATION_TIME}
    secret: ${JWT_SECRET}
