spring:
  application:
    name: no-loose-coins

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
    locations: db/migrations/postgre


server:
  port: ${PORT}

